### ISSUE TITLE
Idea: safer bumps

### ISSUE THREAD

**Issue by dmerejkowsky** [SuperTanker/tbump#4]
Now that we have our new refactoring, we could check that the changes are OK *before* doing anything, thus avoiding the risk of having some files replaced and some other not ...

Food for thought ...

**Comment by theodelrieu** [comment]
A dry-run?

**Comment by dmerejkowsky** [comment]
Yeah but dry run is annoying. 

If you forget about it you blame yourself.
If you use it and it's useless you have to re-run the command.

Nonetheless, a --dry-run option would be nice indeed

**Comment by dmerejkowsky** [comment]
Opened #5 :)

**Comment by cgestes** [comment]
an interactive mode that ask if changes must be applied once they are all displayed?

though about that for replacer.
